# Fluent Bit Parsers Configuration

[PARSER]
    Name        json
    Format      json
    Time_Key    _timestamp
    Time_Format %s%6N
    Time_Keep   On

[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
